service: dynamodb-plugin

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  stage: dev

custom:
  stage: ${opt:stage, self:provider.stage}
  table: mytable

resources:
  Resources:
    MyTestTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "Id"
            AttributeType: "S"
          -
            AttributeName: "Timestamp"
            AttributeType: "N"
        KeySchema:
          -
            AttributeName: "Id"
            KeyType: "HASH"
          -
            AttributeName: "Timestamp"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: "mytest-${self:custom.stage}"
